apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-0806 
  janus-idp.io/tekton: test-0806
  backstage.io/kubernetes-id: test-0806
  backstage.io/kubernetes-namespace: rhdh 
  app.kubernetes.io/part-of: test-0806
resources: 
- application-dev.yaml